# Generated by Django 5.2.7 on 2025-10-08 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=datetime.datetime(2025, 10, 8, 17, 1, 41, 636071, tzinfo=datetime.timezone.utc), editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='home_commen_post_id_d25118_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='home_post_created_fa1fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['username'], name='home_post_usernam_4c1b34_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_id'], name='home_post_post_id_fb61c5_idx'),
        ),
    ]
