# Generated by Django 5.2.7 on 2025-10-08 17:38

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('media_file', models.FileField(upload_to=home.models.user_media_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='home_story_created_1862eb_idx'), models.Index(fields=['username'], name='home_story_usernam_9190bf_idx'), models.Index(fields=['story_id'], name='home_story_story_i_441074_idx')],
            },
        ),
    ]
