# Generated by Django 5.2.7 on 2025-10-08 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='home.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'username'], name='home_like_post_id_8cbec8_idx')],
                'unique_together': {('post', 'username')},
            },
        ),
    ]
