# Generated by Django 5.2.7 on 2025-10-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
