# Generated by Django 5.2.7 on 2025-10-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home', '0006_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField(help_text='Comma-separated ingredients')),
                ('instructions', models.TextField()),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('total_time_mins', models.IntegerField(default=45)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='authentication.googleuser')),
            ],
        ),
    ]
