# Generated by Django 5.2.7 on 2025-10-17 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home', '0008_remove_recipe_image_url_recipe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='authentication.googleuser')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='authentication.googleuser')),
            ],
            options={
                'verbose_name_plural': 'Follows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', 'following'], name='home_follow_followe_89ac7d_idx'), models.Index(fields=['following'], name='home_follow_followi_579a2d_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
